/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPembantu {
  'status' : { 'pending' : null } |
    { 'approved' : null },
  'principal' : Principal,
  'namaKwartirRanting' : string,
}
export interface CreateOrUpdateKwartirRantingInput {
  'kmd' : bigint,
  'kml' : bigint,
  'jambore' : bigint,
  'raimuna' : bigint,
  'ikutLombaTingkatIII' : bigint,
  'siagaPutera' : bigint,
  'siagaPuteri' : bigint,
  'perkemahanBaktiSatuanKarya' : bigint,
  'lombaTingkatII' : bigint,
  'satuanKaryaAktif' : bigint,
  'bazarSiaga' : bigint,
  'masaBakti' : string,
  'mengirimkanUtusanDewanKerja' : bigint,
  'partisipasiKaryaBaktiLebaranC3' : bigint,
  'partisipasiKaryaBaktiLebaranC4' : bigint,
  'namaKetua' : string,
  'rekruitmenPenegakGaruda' : bigint,
  'penegakPutera' : bigint,
  'penegakPuteri' : bigint,
  'nomorSk' : string,
  'partisipasiPenangananBencanaC3' : bigint,
  'partisipasiPenangananBencanaC4' : bigint,
  'memilkiBumiPerkemahan' : boolean,
  'dianpinru' : bigint,
  'karangPamitran' : bigint,
  'namaKwartirRanting' : string,
  'rekruitmenSiagaGaruda' : bigint,
  'lombaGladiTangkasMedan' : bigint,
  'mengirimkanUtusanKpdK' : bigint,
  'gudepPutera' : bigint,
  'gudepPuteri' : bigint,
  'mengirimkanUtusanLpkdk' : bigint,
  'pandegaPutera' : bigint,
  'pandegaPuteri' : bigint,
  'pembina' : bigint,
  'dianpinsat' : bigint,
  'pestaSiaga' : bigint,
  'mediaSosial' : string,
  'rekruitmenPenggalangGaruda' : bigint,
  'anggotaSatgasPramukaPeduli' : bigint,
  'mengirimkanUtusanKpd' : bigint,
  'mengirimkanUtusanKpl' : bigint,
  'mengirimkanUtusanLpk' : bigint,
  'mengirimkanUtusanKpdDewasa' : bigint,
  'partisipasiKaryaBaktiNatalC3' : bigint,
  'partisipasiKaryaBaktiNatalC4' : bigint,
  'orientasiMajelisPembimbing' : bigint,
  'memilikiSekretariat' : boolean,
  'penggalangPutera' : bigint,
  'penggalangPuteri' : bigint,
}
export interface CreateOrUpdatePenilaianInput {
  'skorPotensi' : number,
  'skorKegiatan' : number,
  'skorProfil' : number,
  'kwartirRantingOwner' : Principal,
  'skorTotal' : number,
  'namaKegiatan' : string,
}
export interface KwartirRanting {
  'kmd' : bigint,
  'kml' : bigint,
  'jambore' : bigint,
  'raimuna' : bigint,
  'ikutLombaTingkatIII' : bigint,
  'siagaPutera' : bigint,
  'siagaPuteri' : bigint,
  'perkemahanBaktiSatuanKarya' : bigint,
  'lombaTingkatII' : bigint,
  'satuanKaryaAktif' : bigint,
  'bazarSiaga' : bigint,
  'masaBakti' : string,
  'owner' : Principal,
  'mengirimkanUtusanDewanKerja' : bigint,
  'partisipasiKaryaBaktiLebaranC3' : bigint,
  'partisipasiKaryaBaktiLebaranC4' : bigint,
  'namaKetua' : string,
  'rekruitmenPenegakGaruda' : bigint,
  'penegakPutera' : bigint,
  'penegakPuteri' : bigint,
  'nomorSk' : string,
  'partisipasiPenangananBencanaC3' : bigint,
  'partisipasiPenangananBencanaC4' : bigint,
  'memilkiBumiPerkemahan' : boolean,
  'dianpinru' : bigint,
  'submittedAt' : bigint,
  'karangPamitran' : bigint,
  'namaKwartirRanting' : string,
  'rekruitmenSiagaGaruda' : bigint,
  'lombaGladiTangkasMedan' : bigint,
  'mengirimkanUtusanKpdK' : bigint,
  'gudepPutera' : bigint,
  'gudepPuteri' : bigint,
  'mengirimkanUtusanLpkdk' : bigint,
  'pandegaPutera' : bigint,
  'pandegaPuteri' : bigint,
  'pembina' : bigint,
  'dianpinsat' : bigint,
  'pestaSiaga' : bigint,
  'mediaSosial' : string,
  'rekruitmenPenggalangGaruda' : bigint,
  'anggotaSatgasPramukaPeduli' : bigint,
  'mengirimkanUtusanKpd' : bigint,
  'mengirimkanUtusanKpl' : bigint,
  'mengirimkanUtusanLpk' : bigint,
  'mengirimkanUtusanKpdDewasa' : bigint,
  'partisipasiKaryaBaktiNatalC3' : bigint,
  'partisipasiKaryaBaktiNatalC4' : bigint,
  'orientasiMajelisPembimbing' : bigint,
  'memilikiSekretariat' : boolean,
  'penggalangPutera' : bigint,
  'penggalangPuteri' : bigint,
}
export interface Penilaian {
  'assessedAt' : bigint,
  'assessedBy' : Principal,
  'skorPotensi' : number,
  'skorKegiatan' : number,
  'skorProfil' : number,
  'kwartirRantingOwner' : Principal,
  'skorTotal' : number,
  'namaKegiatan' : string,
}
export type T = [KwartirRanting, [] | [Penilaian]];
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminPembantu' : ActorMethod<[string], undefined>,
  'allKwartirRanting' : ActorMethod<[], Array<KwartirRanting>>,
  'approveAdminPembantu' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateKwartirRanting' : ActorMethod<
    [CreateOrUpdateKwartirRantingInput],
    undefined
  >,
  'createOrUpdatePenilaian' : ActorMethod<
    [CreateOrUpdatePenilaianInput],
    undefined
  >,
  'getAllSortedByScore' : ActorMethod<[], Array<T>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKwartirRantingByOwner' : ActorMethod<[Principal], [] | [KwartirRanting]>,
  'getMyKwartirRanting' : ActorMethod<[], [] | [KwartirRanting]>,
  'getPenilaianForOwner' : ActorMethod<[Principal], [] | [Penilaian]>,
  'isAdminPembantuCheck' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerAdminPembantu' : ActorMethod<[], boolean>,
  'pendingAdminPembantu' : ActorMethod<[], Array<AdminPembantu>>,
  'removeAdminPembantu' : ActorMethod<[Principal], undefined>,
  'submitKwartirRanting' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];