/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdminPembantu {
    status: Variant_pending_approved;
    principal: Principal;
    namaKwartirRanting: string;
}
export type T = [KwartirRanting, Penilaian | null];
export interface Penilaian {
    assessedAt: bigint;
    assessedBy: Principal;
    skorPotensi: number;
    skorKegiatan: number;
    skorProfil: number;
    kwartirRantingOwner: Principal;
    skorTotal: number;
    namaKegiatan: string;
}
export interface CreateOrUpdatePenilaianInput {
    skorPotensi: number;
    skorKegiatan: number;
    skorProfil: number;
    kwartirRantingOwner: Principal;
    skorTotal: number;
    namaKegiatan: string;
}
export interface KwartirRanting {
    kmd: bigint;
    kml: bigint;
    jambore: bigint;
    raimuna: bigint;
    ikutLombaTingkatIII: bigint;
    siagaPutera: bigint;
    siagaPuteri: bigint;
    perkemahanBaktiSatuanKarya: bigint;
    lombaTingkatII: bigint;
    satuanKaryaAktif: bigint;
    bazarSiaga: bigint;
    masaBakti: string;
    owner: Principal;
    mengirimkanUtusanDewanKerja: bigint;
    partisipasiKaryaBaktiLebaranC3: bigint;
    partisipasiKaryaBaktiLebaranC4: bigint;
    namaKetua: string;
    rekruitmenPenegakGaruda: bigint;
    penegakPutera: bigint;
    penegakPuteri: bigint;
    nomorSk: string;
    partisipasiPenangananBencanaC3: bigint;
    partisipasiPenangananBencanaC4: bigint;
    memilkiBumiPerkemahan: boolean;
    dianpinru: bigint;
    submittedAt: bigint;
    karangPamitran: bigint;
    namaKwartirRanting: string;
    rekruitmenSiagaGaruda: bigint;
    lombaGladiTangkasMedan: bigint;
    mengirimkanUtusanKpdK: bigint;
    gudepPutera: bigint;
    gudepPuteri: bigint;
    mengirimkanUtusanLpkdk: bigint;
    pandegaPutera: bigint;
    pandegaPuteri: bigint;
    pembina: bigint;
    dianpinsat: bigint;
    pestaSiaga: bigint;
    mediaSosial: string;
    rekruitmenPenggalangGaruda: bigint;
    anggotaSatgasPramukaPeduli: bigint;
    mengirimkanUtusanKpd: bigint;
    mengirimkanUtusanKpl: bigint;
    mengirimkanUtusanLpk: bigint;
    mengirimkanUtusanKpdDewasa: bigint;
    partisipasiKaryaBaktiNatalC3: bigint;
    partisipasiKaryaBaktiNatalC4: bigint;
    orientasiMajelisPembimbing: bigint;
    memilikiSekretariat: boolean;
    penggalangPutera: bigint;
    penggalangPuteri: bigint;
}
export interface CreateOrUpdateKwartirRantingInput {
    kmd: bigint;
    kml: bigint;
    jambore: bigint;
    raimuna: bigint;
    ikutLombaTingkatIII: bigint;
    siagaPutera: bigint;
    siagaPuteri: bigint;
    perkemahanBaktiSatuanKarya: bigint;
    lombaTingkatII: bigint;
    satuanKaryaAktif: bigint;
    bazarSiaga: bigint;
    masaBakti: string;
    mengirimkanUtusanDewanKerja: bigint;
    partisipasiKaryaBaktiLebaranC3: bigint;
    partisipasiKaryaBaktiLebaranC4: bigint;
    namaKetua: string;
    rekruitmenPenegakGaruda: bigint;
    penegakPutera: bigint;
    penegakPuteri: bigint;
    nomorSk: string;
    partisipasiPenangananBencanaC3: bigint;
    partisipasiPenangananBencanaC4: bigint;
    memilkiBumiPerkemahan: boolean;
    dianpinru: bigint;
    karangPamitran: bigint;
    namaKwartirRanting: string;
    rekruitmenSiagaGaruda: bigint;
    lombaGladiTangkasMedan: bigint;
    mengirimkanUtusanKpdK: bigint;
    gudepPutera: bigint;
    gudepPuteri: bigint;
    mengirimkanUtusanLpkdk: bigint;
    pandegaPutera: bigint;
    pandegaPuteri: bigint;
    pembina: bigint;
    dianpinsat: bigint;
    pestaSiaga: bigint;
    mediaSosial: string;
    rekruitmenPenggalangGaruda: bigint;
    anggotaSatgasPramukaPeduli: bigint;
    mengirimkanUtusanKpd: bigint;
    mengirimkanUtusanKpl: bigint;
    mengirimkanUtusanLpk: bigint;
    mengirimkanUtusanKpdDewasa: bigint;
    partisipasiKaryaBaktiNatalC3: bigint;
    partisipasiKaryaBaktiNatalC4: bigint;
    orientasiMajelisPembimbing: bigint;
    memilikiSekretariat: boolean;
    penggalangPutera: bigint;
    penggalangPuteri: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved {
    pending = "pending",
    approved = "approved"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminPembantu(namaKwartirRanting: string): Promise<void>;
    allKwartirRanting(): Promise<Array<KwartirRanting>>;
    approveAdminPembantu(principal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateKwartirRanting(input: CreateOrUpdateKwartirRantingInput): Promise<void>;
    createOrUpdatePenilaian(input: CreateOrUpdatePenilaianInput): Promise<void>;
    getAllSortedByScore(): Promise<Array<T>>;
    getCallerUserRole(): Promise<UserRole>;
    getKwartirRantingByOwner(owner: Principal): Promise<KwartirRanting | null>;
    getMyKwartirRanting(): Promise<KwartirRanting | null>;
    getPenilaianForOwner(owner: Principal): Promise<Penilaian | null>;
    isAdminPembantuCheck(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerAdminPembantu(): Promise<boolean>;
    pendingAdminPembantu(): Promise<Array<AdminPembantu>>;
    removeAdminPembantu(principal: Principal): Promise<void>;
    submitKwartirRanting(): Promise<void>;
}
import type { AdminPembantu as _AdminPembantu, KwartirRanting as _KwartirRanting, Penilaian as _Penilaian, T as _T, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminPembantu(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminPembantu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminPembantu(arg0);
            return result;
        }
    }
    async allKwartirRanting(): Promise<Array<KwartirRanting>> {
        if (this.processError) {
            try {
                const result = await this.actor.allKwartirRanting();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.allKwartirRanting();
            return result;
        }
    }
    async approveAdminPembantu(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAdminPembantu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAdminPembantu(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateKwartirRanting(arg0: CreateOrUpdateKwartirRantingInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateKwartirRanting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateKwartirRanting(arg0);
            return result;
        }
    }
    async createOrUpdatePenilaian(arg0: CreateOrUpdatePenilaianInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdatePenilaian(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdatePenilaian(arg0);
            return result;
        }
    }
    async getAllSortedByScore(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSortedByScore();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSortedByScore();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKwartirRantingByOwner(arg0: Principal): Promise<KwartirRanting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKwartirRantingByOwner(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKwartirRantingByOwner(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyKwartirRanting(): Promise<KwartirRanting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyKwartirRanting();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyKwartirRanting();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPenilaianForOwner(arg0: Principal): Promise<Penilaian | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPenilaianForOwner(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPenilaianForOwner(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminPembantuCheck(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminPembantuCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminPembantuCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerAdminPembantu(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdminPembantu();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdminPembantu();
            return result;
        }
    }
    async pendingAdminPembantu(): Promise<Array<AdminPembantu>> {
        if (this.processError) {
            try {
                const result = await this.actor.pendingAdminPembantu();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pendingAdminPembantu();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAdminPembantu(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdminPembantu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdminPembantu(arg0);
            return result;
        }
    }
    async submitKwartirRanting(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKwartirRanting();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKwartirRanting();
            return result;
        }
    }
}
function from_candid_AdminPembantu_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminPembantu): AdminPembantu {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_T_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_tuple_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Penilaian]): Penilaian | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KwartirRanting]): KwartirRanting | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        approved: null;
    };
    principal: Principal;
    namaKwartirRanting: string;
}): {
    status: Variant_pending_approved;
    principal: Principal;
    namaKwartirRanting: string;
} {
    return {
        status: from_candid_variant_n13(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        namaKwartirRanting: value.namaKwartirRanting
    };
}
function from_candid_tuple_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_KwartirRanting, [] | [_Penilaian]]): [KwartirRanting, Penilaian | null] {
    return [
        value[0],
        from_candid_opt_n6(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
}): Variant_pending_approved {
    return "pending" in value ? Variant_pending_approved.pending : "approved" in value ? Variant_pending_approved.approved : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminPembantu>): Array<AdminPembantu> {
    return value.map((x)=>from_candid_AdminPembantu_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
