/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AddLampiranInput {
    blob?: ExternalBlob;
    namaFile: string;
    kategoriKegiatan: string;
}
export interface AdminPembantu {
    status: Variant_pending_approved;
    principal: Principal;
    namaKwartirRanting: string;
}
export type T = [KwartirRanting, Penilaian | null];
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Penilaian {
    assessedAt: bigint;
    assessedBy: Principal;
    skorSatuanKarya: number;
    skorDewanKerja: number;
    skorPotensi: number;
    skorKegiatan: number;
    skorPusdiklat: number;
    skorProfil: number;
    kwartirRantingOwner: Principal;
    skorTotal: number;
    namaKegiatan: string;
}
export interface CreateOrUpdatePenilaianInput {
    skorSatuanKarya: number;
    skorDewanKerja: number;
    skorPotensi: number;
    skorKegiatan: number;
    skorPusdiklat: number;
    skorProfil: number;
    kwartirRantingOwner: Principal;
    skorTotal: number;
    namaKegiatan: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface KwartirRanting {
    kmd: bigint;
    kml: bigint;
    jambore: bigint;
    raimuna: bigint;
    ikutLombaTingkatIII: bigint;
    dewanKerjaRantingRapat: bigint;
    siagaPutera: bigint;
    siagaPuteri: bigint;
    perkemahanBaktiSatuanKarya: bigint;
    lombaTingkatII: bigint;
    satuanKaryaAktif: bigint;
    bazarSiaga: bigint;
    masaBakti: string;
    dewanKerjaRantingPeserta: bigint;
    owner: Principal;
    mengirimkanUtusanDewanKerja: bigint;
    partisipasiKaryaBaktiLebaranC3: bigint;
    partisipasiKaryaBaktiLebaranC4: bigint;
    namaKetua: string;
    pusdiklatKegiatan: bigint;
    rekruitmenPenegakGaruda: bigint;
    penegakPutera: bigint;
    penegakPuteri: bigint;
    nomorSk: string;
    satuanKaryaKegiatan: bigint;
    partisipasiPenangananBencanaC3: bigint;
    partisipasiPenangananBencanaC4: bigint;
    memilkiBumiPerkemahan: boolean;
    dianpinru: bigint;
    submittedAt: bigint;
    karangPamitran: bigint;
    namaKwartirRanting: string;
    rekruitmenSiagaGaruda: bigint;
    lombaGladiTangkasMedan: bigint;
    mengirimkanUtusanKpdK: bigint;
    gudepPutera: bigint;
    gudepPuteri: bigint;
    mengirimkanUtusanLpkdk: bigint;
    pandegaPutera: bigint;
    pandegaPuteri: bigint;
    pusdiklatPeserta: bigint;
    pembina: bigint;
    dianpinsat: bigint;
    pestaSiaga: bigint;
    mediaSosial: string;
    rekruitmenPenggalangGaruda: bigint;
    anggotaSatgasPramukaPeduli: bigint;
    mengirimkanUtusanKpd: bigint;
    mengirimkanUtusanKpl: bigint;
    mengirimkanUtusanLpk: bigint;
    mengirimkanUtusanKpdDewasa: bigint;
    dewanKerjaRantingKegiatan: bigint;
    partisipasiKaryaBaktiNatalC3: bigint;
    partisipasiKaryaBaktiNatalC4: bigint;
    orientasiMajelisPembimbing: bigint;
    memilikiSekretariat: boolean;
    penggalangPutera: bigint;
    penggalangPuteri: bigint;
    satuanKaryaPerkemahan: bigint;
}
export interface CreateOrUpdateKwartirRantingInput {
    kmd: bigint;
    kml: bigint;
    jambore: bigint;
    raimuna: bigint;
    ikutLombaTingkatIII: bigint;
    dewanKerjaRantingRapat: bigint;
    siagaPutera: bigint;
    siagaPuteri: bigint;
    perkemahanBaktiSatuanKarya: bigint;
    lombaTingkatII: bigint;
    satuanKaryaAktif: bigint;
    bazarSiaga: bigint;
    masaBakti: string;
    dewanKerjaRantingPeserta: bigint;
    mengirimkanUtusanDewanKerja: bigint;
    partisipasiKaryaBaktiLebaranC3: bigint;
    partisipasiKaryaBaktiLebaranC4: bigint;
    namaKetua: string;
    pusdiklatKegiatan: bigint;
    rekruitmenPenegakGaruda: bigint;
    penegakPutera: bigint;
    penegakPuteri: bigint;
    nomorSk: string;
    satuanKaryaKegiatan: bigint;
    partisipasiPenangananBencanaC3: bigint;
    partisipasiPenangananBencanaC4: bigint;
    memilkiBumiPerkemahan: boolean;
    dianpinru: bigint;
    karangPamitran: bigint;
    namaKwartirRanting: string;
    rekruitmenSiagaGaruda: bigint;
    lombaGladiTangkasMedan: bigint;
    mengirimkanUtusanKpdK: bigint;
    gudepPutera: bigint;
    gudepPuteri: bigint;
    mengirimkanUtusanLpkdk: bigint;
    pandegaPutera: bigint;
    pandegaPuteri: bigint;
    pusdiklatPeserta: bigint;
    pembina: bigint;
    dianpinsat: bigint;
    pestaSiaga: bigint;
    mediaSosial: string;
    rekruitmenPenggalangGaruda: bigint;
    anggotaSatgasPramukaPeduli: bigint;
    mengirimkanUtusanKpd: bigint;
    mengirimkanUtusanKpl: bigint;
    mengirimkanUtusanLpk: bigint;
    mengirimkanUtusanKpdDewasa: bigint;
    dewanKerjaRantingKegiatan: bigint;
    partisipasiKaryaBaktiNatalC3: bigint;
    partisipasiKaryaBaktiNatalC4: bigint;
    orientasiMajelisPembimbing: bigint;
    memilikiSekretariat: boolean;
    penggalangPutera: bigint;
    penggalangPuteri: bigint;
    satuanKaryaPerkemahan: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Lampiran {
    id: string;
    owner: Principal;
    blob?: ExternalBlob;
    namaFile: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
    kategoriKegiatan: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved {
    pending = "pending",
    approved = "approved"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminPembantu(namaKwartirRanting: string): Promise<void>;
    addLampiran(input: AddLampiranInput): Promise<string>;
    allKwartirRanting(): Promise<Array<KwartirRanting>>;
    approveAdminPembantu(principal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateKwartirRanting(input: CreateOrUpdateKwartirRantingInput): Promise<void>;
    createOrUpdatePenilaian(input: CreateOrUpdatePenilaianInput): Promise<void>;
    deleteLampiran(id: string): Promise<void>;
    deletePenilaian(owner: Principal): Promise<void>;
    getAllLampiran(): Promise<Array<Lampiran>>;
    getAllSortedByScore(): Promise<Array<T>>;
    getCallerUserRole(): Promise<UserRole>;
    getKwartirRantingByOwner(owner: Principal): Promise<KwartirRanting | null>;
    getLampiranByOwner(owner: Principal): Promise<Array<Lampiran>>;
    getMyKwartirRanting(): Promise<KwartirRanting | null>;
    getMyLampiran(): Promise<Array<Lampiran>>;
    getPenilaianForOwner(owner: Principal): Promise<Penilaian | null>;
    isAdminPembantuCheck(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerAdminPembantu(): Promise<boolean>;
    pendingAdminPembantu(): Promise<Array<AdminPembantu>>;
    removeAdminPembantu(principal: Principal): Promise<void>;
    submitKwartirRanting(): Promise<void>;
}
import type { AddLampiranInput as _AddLampiranInput, AdminPembantu as _AdminPembantu, ExternalBlob as _ExternalBlob, KwartirRanting as _KwartirRanting, Lampiran as _Lampiran, Penilaian as _Penilaian, T as _T, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminPembantu(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminPembantu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminPembantu(arg0);
            return result;
        }
    }
    async addLampiran(arg0: AddLampiranInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLampiran(await to_candid_AddLampiranInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLampiran(await to_candid_AddLampiranInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async allKwartirRanting(): Promise<Array<KwartirRanting>> {
        if (this.processError) {
            try {
                const result = await this.actor.allKwartirRanting();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.allKwartirRanting();
            return result;
        }
    }
    async approveAdminPembantu(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAdminPembantu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAdminPembantu(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateKwartirRanting(arg0: CreateOrUpdateKwartirRantingInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateKwartirRanting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateKwartirRanting(arg0);
            return result;
        }
    }
    async createOrUpdatePenilaian(arg0: CreateOrUpdatePenilaianInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdatePenilaian(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdatePenilaian(arg0);
            return result;
        }
    }
    async deleteLampiran(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLampiran(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLampiran(arg0);
            return result;
        }
    }
    async deletePenilaian(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePenilaian(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePenilaian(arg0);
            return result;
        }
    }
    async getAllLampiran(): Promise<Array<Lampiran>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLampiran();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLampiran();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSortedByScore(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSortedByScore();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSortedByScore();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKwartirRantingByOwner(arg0: Principal): Promise<KwartirRanting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKwartirRantingByOwner(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKwartirRantingByOwner(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLampiranByOwner(arg0: Principal): Promise<Array<Lampiran>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLampiranByOwner(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLampiranByOwner(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyKwartirRanting(): Promise<KwartirRanting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyKwartirRanting();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyKwartirRanting();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLampiran(): Promise<Array<Lampiran>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLampiran();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLampiran();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPenilaianForOwner(arg0: Principal): Promise<Penilaian | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPenilaianForOwner(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPenilaianForOwner(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminPembantuCheck(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminPembantuCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminPembantuCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerAdminPembantu(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdminPembantu();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdminPembantu();
            return result;
        }
    }
    async pendingAdminPembantu(): Promise<Array<AdminPembantu>> {
        if (this.processError) {
            try {
                const result = await this.actor.pendingAdminPembantu();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pendingAdminPembantu();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAdminPembantu(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdminPembantu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdminPembantu(arg0);
            return result;
        }
    }
    async submitKwartirRanting(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKwartirRanting();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKwartirRanting();
            return result;
        }
    }
}
function from_candid_AdminPembantu_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminPembantu): AdminPembantu {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Lampiran_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lampiran): Promise<Lampiran> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_T_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_tuple_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Penilaian]): Penilaian | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KwartirRanting]): KwartirRanting | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    blob: [] | [_ExternalBlob];
    namaFile: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
    kategoriKegiatan: string;
}): Promise<{
    id: string;
    owner: Principal;
    blob?: ExternalBlob;
    namaFile: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
    kategoriKegiatan: string;
}> {
    return {
        id: value.id,
        owner: value.owner,
        blob: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.blob)),
        namaFile: value.namaFile,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy,
        kategoriKegiatan: value.kategoriKegiatan
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        approved: null;
    };
    principal: Principal;
    namaKwartirRanting: string;
}): {
    status: Variant_pending_approved;
    principal: Principal;
    namaKwartirRanting: string;
} {
    return {
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        namaKwartirRanting: value.namaKwartirRanting
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_KwartirRanting, [] | [_Penilaian]]): [KwartirRanting, Penilaian | null] {
    return [
        value[0],
        from_candid_opt_n21(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
}): Variant_pending_approved {
    return "pending" in value ? Variant_pending_approved.pending : "approved" in value ? Variant_pending_approved.approved : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lampiran>): Promise<Array<Lampiran>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Lampiran_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminPembantu>): Array<AdminPembantu> {
    return value.map((x)=>from_candid_AdminPembantu_n26(_uploadFile, _downloadFile, x));
}
async function to_candid_AddLampiranInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddLampiranInput): Promise<_AddLampiranInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob?: ExternalBlob;
    namaFile: string;
    kategoriKegiatan: string;
}): Promise<{
    blob: [] | [_ExternalBlob];
    namaFile: string;
    kategoriKegiatan: string;
}> {
    return {
        blob: value.blob ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.blob)) : candid_none(),
        namaFile: value.namaFile,
        kategoriKegiatan: value.kategoriKegiatan
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
